### ISSUE TITLE
Missions with no icons show with no icon

### ISSUE THREAD

**Issue by KnightMiner** [itb-community/ITB-Easy-Edit#2]
Using modpack v0.8.1

Currently, missions in easy edit with no icon show with no icon instead of a missing icon
![image](https://user-images.githubusercontent.com/12155288/181393112-eb6df1b7-4d7d-4f20-b783-b95949a9ea2c.png)

This makes it very hard to see those missions.

Unknown missions show with a missing icon, so probably just need some default icon

**Comment by Lemonymous** [comment]
#4 Looks to solve this issue
