### ISSUE TITLE
Islands not resetting to default if a mod is disabled

### ISSUE THREAD

**Issue by tos-x** [itb-community/ITB-Easy-Edit#22]
Need to determine the exact steps, but I've encountered several crashes when trying to click the `World Editor` menu; it appears to happen after these steps (roughly):

1. Have a mod with a custom island enabled
2. Set that island to be 1 of the 4 in `World Editor` (I usually do Pinnacle, but I assume any would work)
3. Restart?
4. Disable the mod with the custom island
5. Restart
6. Try to click `World Editor`; game will crash with error.txt contents: `...modLoaderExtensions/mods/easyEdit/ui/editor_world.lua:274: attempt to index field 'data' (a nil value)`

When reviewing easyEdit profile data, `world.lua` still shows the disabled island's name; but since it doesn't exist, the above error occurs when it tries to index it.

**Comment by Lemonymous** [comment]
Addressed by #25
