### ISSUE TITLE
Add Randomize Islands Feature

### ISSUE THREAD

**Issue by NamesAreHard6600** [itb-community/ITB-Easy-Edit#27]
Many people have requested a feature that allows you to randomize the islands. Some different methods I am considering. 
1. Create a new island in easyedit that is the random island. When you drag this into the island editor, that island would be randomized upon starting a new game. This would be ideal, but I know that whenever you change islands you have to restart the game to load in the right sprites. This may make this method not work. 
2. Create a randomize button within the easyedit menu that randomizes all the islands to set islands. This would eliminate the previous problem because it would give you the warning that the game needs to be restarted. However, it would have to be rerandomized every game. If necessary though, it is what it is. I think this will be the method we have to use. 

Note: It would also be nice if there were a checkbox between pure random, and controlled random. Pure random would allow for duplicate islands while controlled random would not. If not possible, I would just stick to controlled. (kinda like chaos roll and balanced roll)

**Comment by NamesAreHard6600** [comment]
#28

**Comment by KnightMiner** [comment]
The approach I was thinking was a checkbox of some sort that randomizes islands on game start. Would need to check there is no active run before doing so. That said, it would potentially have a lot of edge cases, so not sure that approach is worth pursuing.

In any case, a random button within the menu is a good feature to have.
